#!/usr/bin/env python

"""
Entry point for starting a local test HCA staging API server.
"""

import os
import sys
import logging
import argparse

from chalice.cli import CLIFactory, run_local_server

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--port", type=int, default=5000)
parser.add_argument("--no-debug", dest="debug", action="store_false",
                    help="Disable Chalice/Connexion/Flask debug mode")
parser.add_argument("--project-dir", help=argparse.SUPPRESS,
                    default=os.path.join(os.path.dirname(__file__), "chalice"))
parser.add_argument("--log-level",
                    help=str([logging.getLevelName(i) for i in range(0, 60, 10)]),
                    choices={logging.getLevelName(i) for i in range(0, 60, 10)},
                    default=logging.DEBUG)
args = parser.parse_args()

logging.basicConfig(level=args.log_level, stream=sys.stderr)

chalice_app = CLIFactory(project_dir=args.project_dir, debug=args.debug).load_chalice_app()
run_local_server(chalice_app, port=args.port)
