#!/usr/bin/env python3.7

import os
import sys

if __name__ == '__main__':  # noqa
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))  # noqa
    sys.path.insert(0, pkg_root)  # noqa

from uploadctl.cli import UploadctlCLI

UploadctlCLI()
